
#These configurations are only for the client side
[client]
	#If true, will pause the game while the player is in the editor.
	#Only works in Singleplayer mode.
	doesGuiPauseGame = true
	#If true, notifications about the editor (modifications applied, command copied, etc..) will be shown at the top-left corner of the screen.
	showEditorNotifications = true
	#If true, notifications about the clipboard (clipboard loaded from disk / saved to disk) will be shown at the top-left corner of the screen.
	showClipboardNotifications = false
	#If true, the editor will only open if the player is in creative mode.
	creativeModeOnly = true

