
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.waila]
		enable_compat_waila = true

	[Compatibility.bloodmagic]
		enable_compat_bloodmagic = true

